//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string MASACH { get; set; }
        public string MAHOADON { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIATIEN { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
        public string NHANVIEN { get; set; }
        public string MACHITIETHD { get; set; }
    }
}
