//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string MATG { get; set; }
        public string TENLINHVUC { get; set; }
        public string TENLOAISACH { get; set; }
        public Nullable<int> GIAMUA { get; set; }
        public Nullable<int> GIABIA { get; set; }
        public Nullable<int> LANTAIBAN { get; set; }
        public string TENNHAXUATBAN { get; set; }
        public Nullable<System.DateTime> NAMXUATBAN { get; set; }
    }
}
